version: '8.1'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - notes-network
    

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    networks:
      - notes-network

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    networks:
      - notes-network
    depends_on:
      - backend
      - frontend


volumes:
  pg_data:
  static_volume:

networks:
  notes-network:
    driver: bridge
